### ISSUE TITLE
Feature: Automating FRR network expansion

### ISSUE THREAD

**Issue by bbros-dev** [bmullan/CIAB.Full-Mesh.VPN.Wireguard.FRR.BGP.VXLAN.Internet.Overlay.Architecture#2]
Thanks for your effort in making this demo. As well as making it open source.

I wonder if the following would work?

Appreciate any insights or suggestions.

It would seem to simplify the FRR configuration file, but also appear to make the CIAB network "grow" automagically as new nodes are added - the list of node in FRR config don't need to be updated which appears to be the case now.

Of course the WireGuard configuration would need to be updated, but one could work around this by configuring WG for the maximum expected number of nodes.  

The same workaround (pre-listing all possible future IPs) is possible for FRR and this snippet seems to (from reading docs) eliminate the need for the FRR workaround.

```bash
router bgp 64512
  bgp router-id 172.20.10.193
  bgp cluster-id 172.20.10.193
  bgp log-neighbor-changes
  no bgp default ipv4-unicast
  neighbor ciab peer-group
  neighbor ciab remote-as 64512
  neighbor ciab capability extended-nexthop
  neighbor ciab update-source 172.20.10.193
  bgp listen range 172.20.10/24 peer-group ciab
  !
  address-family l2vpn evpn
   neighbor ciab activate
   neighbor ciab route-reflector-client
  exit-address-family
  !
!
```

This would replace the two sections with extensive listings:

```bash
neighbor 172.20.10.200 remote-as 64512
neighbor 172.20.10.147 remote-as 64512
neighbor 172.20.10.102 remote-as 64512
....
neighbor 172.20.10.200 route-reflector-client
neighbor 172.20.10.147 route-reflector-client
neighbor 172.20.10.102 route-reflector-client
neighbor 172.20.10.108 route-reflector-client
```

**Comment by bmullan** [comment]
@bbros-dev (can you email me directly **bmullan.mail@gmail.com**) I see you are in Minnesota so with the deep freeze maybe you could find some time to talk about all this for a bit (I grew up in Iowa but live in North Carolina).

**Comment by bbros-dev** [comment]
Have sent a note.

**Comment by bbros-dev** [comment]
Unfortunately, we no longer have time to devote to resolving this issue.  

Closing, but happy for anyone to reopen - we didn't want to be thought of just opening up to-do lists for others.
