### ISSUE TITLE
Feature: Script distribution via release archives

### ISSUE THREAD

**Issue by bbros-dev** [bmullan/CIAB.Full-Mesh.VPN.Wireguard.FRR.BGP.VXLAN.Internet.Overlay.Architecture#4]
Not sure if you'd be open to any PR's changing any of the following:

1. Extract scripts to `scripts` folder: Allows issue reports and PR's to the scripts.
2. Extract PDF to Markdown: Allows issue reports and PR's to the documentation, see issue #3.
3. Alter install instructions to download a release archive.

**Comment by bmullan** [comment]
Thanks 
Any help is  appreciated.

**Comment by bbros-dev** [comment]
Closed by RFC #11
